'use strict';
  const userFilters = () => {
    const params = p();
    return { role: ['all', 'student', 'teacher', 'administrator'].includes(params.get('role')) ? params.get('role') : 'all', status: ['all', 'active', 'inactive'].includes(params.get('status')) ? params.get('status') : 'all', q: String(params.get('q') || '').trim().toLowerCase() };
  };
  function usersPage() {
    const filters = userFilters();
    const classes = Store.listClasses();
    const users = Store.listUsers().filter((user) => (filters.role === 'all' || user.role === filters.role) && (filters.status === 'all' || user.status === filters.status) && (!filters.q || `${user.fullName} ${user.id}`.toLowerCase().includes(filters.q)));
    root.innerHTML = `<div class="page-enter">${pageHead('People directory', 'Users', 'Manage students, teachers and administrators without turning the page into a giant form.', `<button class="btn btn-primary" data-modal="user-create">${ICON.plus} Add user</button>`)}
      <section class="surface overflow-hidden"><div class="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row lg:items-center"><div class="relative min-w-0 flex-1"><label class="sr-only" for="user-search">Search users</label><input id="user-search" class="field" value="${e(filters.q)}" placeholder="Search by name or ID"></div><div class="segmented overflow-x-auto">${['all', 'student', 'teacher', 'administrator'].map((role) => `<button type="button" data-user-role="${role}" aria-pressed="${filters.role === role}">${role === 'all' ? 'All roles' : role}</button>`).join('')}</div><div class="segmented">${['all', 'active', 'inactive'].map((status) => `<button type="button" data-user-status="${status}" aria-pressed="${filters.status === status}">${status}</button>`).join('')}</div></div>
      ${users.length ? `<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Class</th><th>Status</th><th>Joined</th><th></th></tr></thead><tbody>${users.map((user) => { const cls = classes.find((item) => item.id === user.classId); return `<tr><td><button class="flex items-center gap-3 text-left" data-detail="user" data-id="${e(user.id)}"><span class="avatar size-9 text-xs">${e(user.fullName.split(' ').slice(0, 2).map((part) => part[0]).join(''))}</span><span><strong class="block text-slate-900">${e(user.fullName)}</strong><span class="text-xs text-slate-500">${e(user.id)}</span></span></button></td><td><span class="badge badge-neutral capitalize">${e(user.role)}</span></td><td>${e(cls?.name || '—')}</td><td>${statusBadge(user.status)}</td><td class="whitespace-nowrap">${new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium' }).format(new Date(user.joinedAt))}</td><td><button class="icon-btn size-9" data-detail="user" data-id="${e(user.id)}" aria-label="Manage ${e(user.fullName)}">${ICON.more}</button></td></tr>`; }).join('')}</tbody></table></div>` : empty('No matching users', 'Adjust the filters or add a new person.', ART.people, `<button class="btn btn-primary" data-modal="user-create">Add user</button>`)}
      </section></div>`;
  }

  function classesPage() {
    const classes = Store.listClasses();
    const users = Store.listUsers();
    const sessions = Store.listSessions();
    root.innerHTML = `<div class="page-enter">${pageHead('Academic structure', 'Classes', 'Manage cohorts, streams, rooms and capacity with compact presets.', `<button class="btn btn-primary" data-modal="class-create">${ICON.plus} New class</button>`)}
      <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">${classes.map((cls) => { const count = users.filter((user) => user.classId === cls.id && user.role === 'student').length; const exams = sessions.filter((s) => s.classLevel === cls.classLevel).length; const pct = Math.min(100, Math.round(count / cls.capacity * 100)); return `<article class="surface-raised overflow-hidden"><div class="h-1.5 bg-gradient-to-r ${cls.stream === 'Science' ? 'from-blue-500 to-cyan-400' : cls.stream === 'Arts' ? 'from-violet-500 to-fuchsia-400' : cls.stream === 'Social Science' ? 'from-teal-500 to-emerald-400' : 'from-amber-400 to-orange-400'}"></div><div class="p-5"><div class="flex items-start justify-between gap-3"><div><span class="badge badge-neutral">${e(cls.classLevel)}</span><h3 class="mt-3 font-display text-lg font-extrabold text-slate-950">${e(cls.name)}</h3><p class="mt-1 text-xs text-slate-500">${e(cls.stream)} · ${e(cls.room || 'Room not set')}</p></div><button class="icon-btn size-9" data-detail="class" data-id="${e(cls.id)}" aria-label="Manage ${e(cls.name)}">${ICON.more}</button></div><div class="mt-5 grid grid-cols-2 gap-2"><div class="mini-metric"><span>Students</span><strong>${count}/${cls.capacity}</strong></div><div class="mini-metric"><span>Exam configs</span><strong>${exams}</strong></div></div><div class="mt-4"><div class="mb-1.5 flex justify-between text-[11px] font-bold text-slate-500"><span>Capacity</span><span>${pct}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></div></div></article>`; }).join('')}</div></div>`;
  }

  function examTable(sessions) {
    return `<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Exam</th><th>Coverage</th><th>Paper</th><th>Status</th><th>Schedule</th><th></th></tr></thead><tbody>${sessions.map((session) => `<tr><td><button class="text-left" data-detail="exam" data-id="${e(session.id)}"><strong class="block max-w-xs text-slate-900">${e(session.title)}</strong><span class="mt-1 block text-xs text-slate-500">${e(session.classLevel)} · ${e(Store.getModeLabel(session.mode))}</span></button></td><td class="max-w-xs">${e(coverage(session))}</td><td><strong class="tabular-nums text-slate-800">${session.questionCount}</strong><span class="block text-xs text-slate-500">${session.durationMinutes} min</span></td><td>${statusBadge(sessionState(session))}</td><td class="whitespace-nowrap text-xs">${e(session.startsAt ? formatDate(session.startsAt) : 'Open access')}</td><td><button class="icon-btn size-9" data-detail="exam" data-id="${e(session.id)}" aria-label="Manage ${e(session.title)}">${ICON.more}</button></td></tr>`).join('')}</tbody></table></div>`;
  }

  function examsPage() {
    const status = ['all', 'open', 'scheduled', 'draft', 'closed'].includes(p().get('status')) ? p().get('status') : 'all';
    const all = Store.listSessions();
    const sessions = status === 'all' ? all : all.filter((item) => sessionState(item) === status);
    root.innerHTML = `<div class="page-enter">${pageHead('Assessment operations', 'Exams', 'Build, distribute and monitor examination sessions from one operational registry.', `<button class="btn btn-primary" data-open-exam-wizard>${ICON.plus} Create exam</button>`)}<section class="surface overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><div class="segmented overflow-x-auto">${['all', 'open', 'scheduled', 'draft', 'closed'].map((item) => `<button type="button" data-exam-status="${item}" aria-pressed="${status === item}">${item}</button>`).join('')}</div><span class="badge badge-neutral">${sessions.length} shown</span></div>${sessions.length ? examTable(sessions) : empty('No exams in this view', 'Create an examination or change the status filter.', ART.auth, `<button class="btn btn-primary" data-open-exam-wizard>Create exam</button>`)}</section></div>`;
  }

  const qFilters = () => ({ subject: p().get('subject') || 'all', level: p().get('level') || 'all', type: p().get('type') || 'all' });
  function questionsPage() {
    const filters = qFilters();
    const subjects = data.subjectCatalog;
    const questions = data.questions.filter((q) => (filters.subject === 'all' || q.subjectCode === filters.subject) && (filters.level === 'all' || q.levels.includes(filters.level)) && (filters.type === 'all' || q.type === filters.type));
    root.innerHTML = `<div class="page-enter">${pageHead('Question intelligence', 'Question bank', 'Filter by curriculum domain, preview question structures and add locally authored items.', `<button class="btn btn-primary" data-modal="question-create">${ICON.plus} Add question</button>`)}<div class="mb-4 grid gap-3 lg:grid-cols-[1fr_auto_auto]"><label><span class="sr-only">Subject filter</span><select class="field" id="question-subject-filter"><option value="all">All subjects</option>${subjects.map((s) => `<option value="${e(s.code)}" ${filters.subject === s.code ? 'selected' : ''}>${e(s.label)}</option>`).join('')}</select></label><div class="segmented">${['all', 'SS1', 'SS2', 'SS3'].map((level) => `<button type="button" data-q-level="${level}" aria-pressed="${filters.level === level}">${level === 'all' ? 'All classes' : level}</button>`).join('')}</div><div class="segmented">${['all', 'single', 'multi', 'boolean', 'fill'].map((type) => `<button type="button" data-q-type="${type}" aria-pressed="${filters.type === type}">${type}</button>`).join('')}</div></div><section class="surface overflow-hidden">${questions.length ? `<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Question</th><th>Subject</th><th>Levels</th><th>Type</th><th>Domain</th><th></th></tr></thead><tbody>${questions.slice(0, 100).map((q) => `<tr><td class="max-w-xl"><button class="text-left" data-detail="question" data-id="${q.id}"><strong class="line-clamp-2 text-slate-900">${e(q.prompt)}</strong><span class="mt-1 block text-xs text-slate-500">#${q.id}${q.custom ? ' · Custom' : ''}</span></button></td><td>${e(q.subject)}</td><td>${q.levels.map((level) => `<span class="badge badge-neutral mr-1">${e(level)}</span>`).join('')}</td><td><span class="badge badge-brand">${e(q.type)}</span></td><td>${e(q.domain)}</td><td><button class="icon-btn size-9" data-detail="question" data-id="${q.id}" aria-label="Preview question ${q.id}">${ICON.more}</button></td></tr>`).join('')}</tbody></table></div>` : empty('No matching questions', 'Change the filters or add a local question.', ART.question)}</section></div>`;
  }

  function reportsPage() {
    const attempts = Store.getAttempts();
    const classes = Store.listClasses();
    const completed = attempts.filter((a) => a.submittedAt).length;
    const completion = attempts.length ? Math.round(completed / attempts.length * 100) : 0;
    root.innerHTML = `<div class="page-enter">${pageHead('Insights', 'Reports', 'A compact prototype view of participation, completion and class activity.', `<button class="btn btn-secondary" data-report-refresh>Refresh data</button>`)}<section class="kpi-grid">${kpi('Attempts', attempts.length, 'All browser-local records', 'brand')}${kpi('Completed', completed, `${completion}% completion`, 'teal')}${kpi('In progress', attempts.filter((a) => a.startedAt && !a.submittedAt).length, 'Open candidate states', 'amber')}${kpi('Classes', classes.length, 'Configured cohorts', 'violet')}</section><div class="mt-5 grid gap-5 xl:grid-cols-12"><section class="surface overflow-hidden xl:col-span-7"><div class="border-b border-slate-200 px-5 py-4"><p class="eyebrow">Participation</p><h3 class="section-title mt-1">Attempts by class</h3></div><div id="class-chart" class="min-h-72 p-3"></div></section><section class="surface-brand relative overflow-hidden p-6 xl:col-span-5"><div class="relative z-10 max-w-xs"><span class="badge badge-success">Completion</span><strong class="mt-4 block font-display text-5xl font-extrabold tracking-tight text-slate-950">${completion}%</strong><p class="mt-3 text-sm leading-6 text-slate-600">Submitted attempts compared with all started attempts stored on this browser.</p></div><img src="${ART.student}" alt="Student reviewing a chart on a laptop" class="absolute bottom-0 right-0 h-64 w-56 object-contain opacity-90" loading="lazy"></section></div></div>`;
    const host = document.getElementById('class-chart');
    if (host && window.ApexCharts) {
      const labels = ['SS1', 'SS2', 'SS3'];
      const chart = new ApexCharts(host, { chart: { type: 'bar', height: 275, toolbar: { show: false }, fontFamily: 'DM Sans, sans-serif' }, series: [{ name: 'Attempts', data: labels.map((level) => attempts.filter((a) => a.classLevel === level).length) }], colors: ['#315efb'], plotOptions: { bar: { borderRadius: 6, columnWidth: '42%' } }, dataLabels: { enabled: false }, grid: { borderColor: '#e5ecf5', strokeDashArray: 4 }, xaxis: { categories: labels, axisBorder: { show: false }, axisTicks: { show: false } }, yaxis: { min: 0, labels: { formatter: (value) => Number.isInteger(value) ? value : '' } } });
      chart.render(); charts.push(chart);
    }
  }

  function settingsPage() {
    root.innerHTML = `<div class="page-enter">${pageHead('Workspace configuration', 'Settings', 'Control browser-local prototype records and understand what requires a production backend.')}<div class="grid gap-5 xl:grid-cols-12"><section class="surface overflow-hidden xl:col-span-8"><div class="border-b border-slate-200 px-5 py-4"><p class="eyebrow">Local data</p><h3 class="section-title mt-1">Prototype storage</h3></div><div class="divide-y divide-slate-100">${[
      ['Exam sessions', `${Store.listSessions().length} stored`, 'sessions'], ['Candidate attempts', `${Store.getAttempts().length} stored`, 'attempts'], ['Custom questions', `${Store.listCustomQuestions().length} stored`, 'questions']
    ].map(([title, detail, action]) => `<div class="flex items-center justify-between gap-4 p-4"><div><strong class="text-sm text-slate-900">${title}</strong><p class="mt-1 text-xs text-slate-500">${detail}</p></div><button class="btn btn-secondary btn-sm" data-clear-local="${action}">Clear</button></div>`).join('')}<div class="flex items-center justify-between gap-4 p-4"><div><strong class="text-sm text-rose-700">Reset entire prototype</strong><p class="mt-1 text-xs text-slate-500">Sessions, users, classes, attempts, questions and student states.</p></div><button class="btn btn-danger" data-modal="reset-all">Reset all</button></div></div></section><aside class="surface-brand overflow-hidden xl:col-span-4"><div class="illustration-well m-4 p-4"><img src="${ART.auth}" alt="Authentication fields representing production account security" class="mx-auto h-36 w-auto" loading="lazy"></div><div class="p-5 pt-1"><span class="badge badge-warning">Production boundary</span><h3 class="mt-3 font-display text-lg font-extrabold text-slate-950">LocalStorage is prototype persistence.</h3><p class="mt-2 text-sm leading-6 text-slate-600">Real administration needs authenticated roles, server-issued session tokens and centralized candidate records.</p></div></aside></div></div>`;
  }

