'use strict';
  function questionModal() {
    const subjects = data.subjectCatalog;
    const editing = data.questions.find((item) => item.custom && item.id === Number(p().get('edit'))) || null;
    openModal(`${modalHeader('Question authoring', editing ? 'Edit question' : 'Add a question', 'Choose curriculum metadata first, then write only the content that must be authored.')}<form id="question-create-form" class="p-5 sm:p-6"><div class="grid gap-5"><div class="grid gap-4 sm:grid-cols-2"><label><span class="field-label">Subject</span><select id="new-question-subject" class="field mt-2">${subjects.map((s) => `<option value="${e(s.code)}" ${editing?.subjectCode===s.code?'selected':''}>${e(s.label)}</option>`).join('')}</select></label><div><span class="field-label">Question type</span><div class="mt-2 flex flex-wrap gap-2">${['single','boolean','fill'].map((type) => `<button type="button" class="choice-chip" data-new-q-type="${type}" aria-pressed="${editing ? editing.type === type : type === 'single'}">${type}</button>`).join('')}</div></div></div><div><span class="field-label">Class levels</span><div class="mt-2 flex gap-2">${['SS1','SS2','SS3'].map((level) => `<button type="button" class="choice-chip" data-new-q-level="${level}" aria-pressed="${editing ? editing.levels.includes(level) : level === 'SS2'}">${level}</button>`).join('')}</div></div><label><span class="field-label">Question</span><textarea id="new-question-prompt" class="field mt-2 min-h-24" placeholder="Write the question stem" required>${e(editing?.prompt || '')}</textarea></label><div id="new-question-options"><span class="field-label">Answer options</span><div class="mt-2 grid gap-2 sm:grid-cols-2">${['A','B','C','D'].map((letter,index) => `<label><span class="sr-only">Option ${letter}</span><input class="field" data-option-input placeholder="${letter}. Option" value="${e(editing?.options?.[index] || '')}"></label>`).join('')}</div></div><label><span class="field-label">Domain</span><input id="new-question-domain" class="field mt-2" value="${e(editing?.domain || 'Curriculum practice')}" maxlength="60"></label><div id="question-create-error" class="hidden alert alert-danger" role="alert"></div></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn btn-secondary" data-modal-close>Cancel</button><button class="btn btn-primary" type="submit">${editing ? 'Save changes' : 'Add to bank'}</button></div></form>`);
    let type = editing?.type || 'single'; const levels = new Set(editing?.levels || ['SS2']);
    const updateType = () => { document.getElementById('new-question-options').classList.toggle('hidden', type !== 'single'); };
    modal.querySelectorAll('[data-new-q-type]').forEach((button) => button.addEventListener('click', () => { type = button.dataset.newQType; modal.querySelectorAll('[data-new-q-type]').forEach((item) => item.setAttribute('aria-pressed', String(item === button))); updateType(); }));
    modal.querySelectorAll('[data-new-q-level]').forEach((button) => button.addEventListener('click', () => { const level = button.dataset.newQLevel; levels.has(level) ? levels.delete(level) : levels.add(level); button.setAttribute('aria-pressed', String(levels.has(level))); })); updateType();
    document.getElementById('question-create-form').addEventListener('submit', (event) => { event.preventDefault(); const error = document.getElementById('question-create-error'); try { if (!levels.size) throw new Error('Choose at least one class level.'); const subjectCode = document.getElementById('new-question-subject').value; const subject = Data.subjectByCode(data, subjectCode); const prompt = document.getElementById('new-question-prompt').value.trim(); if (!prompt) throw new Error('Write the question stem.'); const base = { subject: subject?.label || subjectCode, subjectCode, domain: document.getElementById('new-question-domain').value || 'Curriculum practice', label: 'Custom question', prompt, type, levels: [...levels], examModes: ['single','mixed','waec'] };
      if (type === 'single') { const options = [...modal.querySelectorAll('[data-option-input]')].map((input) => input.value.trim()).filter(Boolean); if (options.length < 2) throw new Error('Add at least two answer options.'); base.options = options; }
      if (type === 'boolean') base.options = ['True','False'];
      if (type === 'fill') base.fillTemplate = [{ text: prompt + ' ' }, { blank: 'answer' }];
      Store.saveCustomQuestion({ ...base, id: editing?.id }); closeModal(); toast(editing ? 'Question updated.' : 'Question added to the local bank.', 'success'); Data.load().then((payload) => { data = payload; render(); });
    } catch (failure) { error.textContent = failure.message; error.classList.remove('hidden'); } });
  }

  function confirmResetModal() {
    openModal(`${modalHeader('Destructive action', 'Reset all prototype data', 'This affects only the current browser origin.')}<div class="p-5 sm:p-6"><div class="alert alert-danger"><strong>This cannot be undone.</strong><span>Sessions, attempts, user/class changes, custom questions and student states will be cleared.</span></div><div class="mt-6 flex justify-end gap-2"><button class="btn btn-secondary" data-modal-close>Cancel</button><button class="btn btn-danger" data-confirm-reset>Reset prototype</button></div></div>`);
    modal.querySelector('[data-confirm-reset]').addEventListener('click', () => { Store.clearPrototypeData(); closeModal(); toast('Prototype data reset.', 'success'); render(); });
  }

  function userDrawer(id) {
    const user = Store.listUsers().find((item) => item.id === id); if (!user) return;
    const cls = classFor(user.classId); const userAttempts = Store.getAttempts().filter((attempt) => attempt.studentName.toLowerCase() === user.fullName.toLowerCase());
    openDrawer(`<div class="p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div class="flex items-center gap-3"><span class="avatar size-12">${e(user.fullName.split(' ').slice(0,2).map((x) => x[0]).join(''))}</span><div><p class="eyebrow">${e(user.id)}</p><h2 class="font-display text-xl font-extrabold text-slate-950">${e(user.fullName)}</h2></div></div><button class="icon-btn" data-drawer-close aria-label="Close details">${ICON.close}</button></div><div class="mt-6 grid grid-cols-2 gap-3"><div class="mini-metric"><span>Role</span><strong class="capitalize">${e(user.role)}</strong></div><div class="mini-metric"><span>Status</span><strong>${e(user.status)}</strong></div><div class="mini-metric"><span>Class</span><strong>${e(cls?.name || '—')}</strong></div><div class="mini-metric"><span>Attempts</span><strong>${userAttempts.length}</strong></div></div><div class="mt-6 surface-soft p-4"><span class="field-label">Quick actions</span><div class="mt-3 flex flex-wrap gap-2"><button class="btn btn-primary" data-modal="user-create" data-modal-edit="${e(user.id)}">Edit user</button><button class="btn btn-secondary" data-user-toggle="${e(user.id)}" data-next-status="${user.status === 'active' ? 'inactive' : 'active'}">${user.status === 'active' ? 'Suspend' : 'Activate'}</button><button class="btn btn-danger" data-user-delete="${e(user.id)}">Delete user</button></div></div>${user.guardian ? `<div class="mt-5"><p class="eyebrow">Guardian</p><strong class="mt-1 block text-sm text-slate-900">${e(user.guardian)}</strong></div>` : ''}</div>`);
  }
  function classDrawer(id) {
    const cls = Store.listClasses().find((item) => item.id === id); if (!cls) return; const students = Store.listUsers().filter((u) => u.classId === id && u.role === 'student');
    openDrawer(`<div class="p-5 sm:p-6"><div class="flex items-start justify-between"><div><span class="badge badge-brand">${e(cls.classLevel)}</span><h2 class="mt-3 font-display text-xl font-extrabold text-slate-950">${e(cls.name)}</h2><p class="mt-1 text-sm text-slate-500">${e(cls.stream)} · ${e(cls.room || 'Room not set')}</p></div><button class="icon-btn" data-drawer-close aria-label="Close details">${ICON.close}</button></div><div class="mt-6 grid grid-cols-2 gap-3"><div class="mini-metric"><span>Students</span><strong>${students.length}</strong></div><div class="mini-metric"><span>Capacity</span><strong>${cls.capacity}</strong></div></div><div class="mt-6"><p class="eyebrow">Students</p><div class="mt-2 divide-y divide-slate-100 rounded-xl border border-slate-200">${students.slice(0,8).map((u) => `<div class="flex items-center gap-3 p-3"><span class="avatar size-8 text-[10px]">${e(u.fullName.split(' ').slice(0,2).map((x) => x[0]).join(''))}</span><span class="text-sm font-semibold text-slate-800">${e(u.fullName)}</span></div>`).join('') || '<p class="p-4 text-sm text-slate-500">No students assigned.</p>'}</div></div><div class="mt-6 flex flex-wrap gap-2"><button class="btn btn-primary" data-modal="class-create" data-modal-edit="${e(cls.id)}">Edit class</button><button class="btn btn-secondary" data-class-archive="${e(cls.id)}">${cls.status === 'archived' ? 'Restore class' : 'Archive class'}</button><button class="btn btn-danger" data-class-delete="${e(cls.id)}">Delete class</button></div></div>`);
  }
  function examDrawer(id) {
    const session = Store.listSessions().find((item) => item.id === id); if (!session) return; const link = Store.getSessionLink(session, location.href); const attempts = Store.getAttempts().filter((a) => a.sessionId === id);
    openDrawer(`<div class="p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><div class="flex flex-wrap gap-2">${statusBadge(sessionState(session))}<span class="badge badge-neutral">${e(session.classLevel)}</span></div><h2 class="mt-3 font-display text-xl font-extrabold text-slate-950">${e(session.title)}</h2><p class="mt-1 text-sm leading-6 text-slate-500">${e(coverage(session))}</p></div><button class="icon-btn" data-drawer-close aria-label="Close details">${ICON.close}</button></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="mini-metric"><span>Questions</span><strong>${session.questionCount}</strong></div><div class="mini-metric"><span>Duration</span><strong>${session.durationMinutes} min</strong></div><div class="mini-metric"><span>Attempts</span><strong>${attempts.length}</strong></div><div class="mini-metric"><span>Submitted</span><strong>${attempts.filter((a) => a.submittedAt).length}</strong></div></div><div class="illustration-well mt-5 p-4"><div id="session-qr" class="mx-auto max-w-48 rounded-xl bg-white p-3 shadow-sm"></div></div><label class="mt-5 block"><span class="field-label">Dynamic student link</span><input class="field mt-2 text-xs" readonly value="${e(link)}" data-session-link></label><div class="mt-3 flex flex-wrap gap-2"><button class="btn btn-primary" data-copy-link>Copy link</button><a class="btn btn-secondary" href="${e(link)}" target="_blank" rel="noopener">Open student view</a><button class="btn btn-secondary" data-exam-toggle="${e(session.id)}" data-next-status="${session.status === 'closed' ? 'open' : 'closed'}">${session.status === 'closed' ? 'Reopen' : 'Close exam'}</button><button class="btn btn-secondary" data-exam-duplicate="${e(session.id)}">Duplicate</button></div><div class="mt-6 border-t border-slate-200 pt-5"><button class="btn btn-danger" data-exam-delete="${e(session.id)}">Delete exam</button></div></div>`);
    QR.render(document.getElementById('session-qr'), link);
  }
  function questionDrawer(id) {
    const q = data.questions.find((item) => item.id === Number(id)); if (!q) return;
    openDrawer(`<div class="p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><span class="badge badge-brand">${e(q.subject)}</span><h2 class="mt-3 font-display text-xl font-extrabold text-slate-950">Question ${q.id}</h2></div><button class="icon-btn" data-drawer-close aria-label="Close details">${ICON.close}</button></div><div class="mt-6 surface-soft p-5"><p class="text-base font-semibold leading-7 text-slate-900">${e(q.prompt)}</p>${q.options ? `<div class="mt-4 grid gap-2">${q.options.map((option, index) => `<div class="flex gap-3 rounded-xl border border-slate-200 bg-white p-3"><span class="answer-marker">${String.fromCharCode(65 + index)}</span><span class="text-sm text-slate-700">${e(option)}</span></div>`).join('')}</div>` : ''}</div><dl class="mt-5 grid grid-cols-2 gap-3"><div class="mini-metric"><dt>Type</dt><dd>${e(q.type)}</dd></div><div class="mini-metric"><dt>Domain</dt><dd>${e(q.domain)}</dd></div></dl>${q.custom ? `<div class="mt-6 flex gap-2"><button class="btn btn-primary" data-modal="question-create" data-modal-edit="${q.id}">Edit question</button><button class="btn btn-danger" data-question-delete="${q.id}">Delete custom question</button></div>` : `<p class="alert alert-info mt-6">JSON curriculum questions are read-only in this prototype.</p>`}</div>`);
  }

  function notificationsDrawer() {
    const drafts = Store.listSessions().filter((s) => s.status === 'draft');
    const active = Store.getAttempts().filter((a) => a.startedAt && !a.submittedAt);
    openDrawer(`<div class="p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><p class="eyebrow">Activity centre</p><h2 class="mt-1 font-display text-xl font-extrabold text-slate-950">Notifications</h2></div><button class="icon-btn" data-drawer-close aria-label="Close notifications">${ICON.close}</button></div><div class="mt-6 grid gap-3">${drafts.length ? `<div class="alert alert-warning"><span><strong class="block">${drafts.length} draft exam(s)</strong>Finish configuration before distributing access.</span></div>` : ''}${active.length ? `<div class="alert alert-info"><span><strong class="block">${active.length} attempt(s) in progress</strong>Students still have active local exam states.</span></div>` : ''}${!drafts.length && !active.length ? `<div class="alert alert-success"><span><strong class="block">All clear</strong>No draft exams or unfinished attempts need attention.</span></div>` : ''}</div></div>`);
  }
  function profileDrawer() {
    const admin = Store.listUsers().find((u) => u.role === 'administrator');
    openDrawer(`<div class="p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div class="flex items-center gap-3"><span class="avatar size-12">AD</span><div><p class="eyebrow">Signed-in prototype role</p><h2 class="font-display text-xl font-extrabold text-slate-950">${e(admin?.fullName || 'Examination Administrator')}</h2></div></div><button class="icon-btn" data-drawer-close aria-label="Close profile">${ICON.close}</button></div><div class="surface-soft mt-6 p-4"><div class="flex items-center justify-between gap-3"><div><strong class="text-sm text-slate-900">Administrator</strong><p class="mt-1 text-xs text-slate-500">Full prototype access on this browser.</p></div><span class="badge badge-success">Active</span></div></div><div class="alert alert-info mt-5"><span>This is a visual prototype identity. Production authentication and permissions require a backend.</span></div></div>`);
  }

